### PR TITLE
Migrate to VS2017 and support Net Standard 1.6 where possible

### PR DESCRIPTION
**Pull request by nad-au**
Hello, I've created this PR to open a line of conversation and see if there's a possibility of bringing this project up-to-date. We use Banzai on a couple of projects and we're looking to freshen up the code and consider a move to Net Core at some future point. 
I've completed the following:

- Migrated all projects to VS2017
- Attempted to support Net Standard 1.6 on all but a few (due to dependencies)
- Used FluentAssertions instead of Should (almost identical syntax)
- Some minor code clean-up (can return FlowComponent<T> instead of dynamic)
- Cleaned up async tests to return Task instead of void
- Updated packages

I've not completed the following:
- Nuget packaging (still to understand this)

All tests are passing. Let me know if this project is still alive and you're accepting PRs?

### CODE REVIEW

**Comment by eswann** [comment]
Sorry @neildobson-au I've been super busy and haven't used this project in a while now.  I totally missed your PR.  I'll take a look and see if I can complete the updates.

**Comment by nad-au** [comment]
OK thanks. I haven't touched this in a while. Need to review what's happened since NET Standard / NET Core 2.0. Perhaps we consider moving straight to 2.0 as the APIs are more complete. Also I think the NUnit situation has been resolved so all projects can target the same runtime.
We are using Banzai in production so it's important for us this project is kept fresh. I'm happy to do all the legwork, just need a bit of help with CI and packaging.

**Comment by nad-au** [comment]
I've pushed an experimental branch targeting NetStandard 2.0
https://github.com/barnardos-au/Banzai/tree/NetStandard20
All tests passing, however I had an issue with Ninject in that I couldn't upgrade to v3.3 or the v4 beta. Not sure what's happening but I keep getting failed to load assembly exceptions. Tried multiple times including clearing out assembly cache and re-installing packages etc.
Apart from that all good except JSON & Javascript test projects which are dependent on the ClearScript binaries. These don't play nicely with NetStandard so I've left them at 4.6.1. Maybe there's something else we can do here.

**Comment by eric-swann-q2** [comment]
Banzai has been updated to support .Net Standard 2.0.  This PR is no longer applicable.  Thanks for the help!

**Pull request closed without merging**
